### ISSUE TITLE
7-Segment Display displaying wrong segments

### ISSUE THREAD

**Issue by Newguy-ish** [DeltaNedas/anuke-logic#3]
In the example below I shift the 1 to the right every processor, and as you can see the 4th-6th displays show more segments than needed.
![IMG_20210504_151241](https://user-images.githubusercontent.com/78880071/117011022-b216d700-aced-11eb-84d1-ef1de45607cb.jpg)

Schematic:
bXNjaAF4nIWQP0sDMRTAXy6p/V/FQRyF+q/YayscuIpdVEQcdO95F2rw7nIkLepU/AaODg4OjoJfow5OfhJ34UziQbkOvZCEX957v0cSINCwgERuSGH1QNKh7dOQR3Ik3BHjEVR9Kj3BYnMAAssh8wS3Y8E9KiUXsO5G41tqB3zIPPu/AZNx4D5AlQXBOGSRO1JltZjfUWFLPhYeBYA1tQA11Na9f/H8weDpvHXa/riY7n1dHX+2O9OTd+eyB7jfeXWauHj2/PiTTOCoWX/D2sTa7C0yUR9n1c1ULWh1f5Fq9fGcu5W6xTxXDXKddbdTt5zvOmBl3Z3UreY9V6koq+6maj3vjx2Ye2xLmQgQ6AnIoKWxYpBo9A0uabwxWNK4YrCiccNgTeMhtkDdBCXfkwRjhcgUExMms3ChZOkwQPJrUqVZqjyXqs1Sdd1Mhf8ANEO5Xw==

**Comment by deltanedas** [comment]
binary literals are prefixed with `0b`, "0001000" is definitely not a single 8 bit
