### ISSUE TITLE
Proc add doesn't work.

### ISSUE THREAD

**Issue by NotYourFox** [DeltaNedas/anuke-logic#4]
Hello! I'm using this mod for a big in-game project. I needed a proc add function to gather some code segments into one processor. It turned out, that the proc add function doesn't do anything (I've tried many ways to use it). Please help.

**Comment by NotYourFox** [comment]
And looks like I've found an issue in your code, which breaks a function, I can show it if you want to. But I can be wrong, I'm just giving my opinion, because I extremely need this function to work.

**Comment by deltanedas** [comment]
uh yeah that issue would help
