### ISSUE TITLE
Crash when adding block to in-game editor

### ISSUE THREAD

**Issue by UOBW** [DeltaNedas/anuke-logic#5]
Hello.
I found this mod in the Mindustry mod-browser. I tried it out, but when I tap on the add button in the in-game editor, the game crashes. Here is the error:
![MindustryCrash](https://user-images.githubusercontent.com/76259564/125079900-6f45f680-e0c4-11eb-8c73-d0e99a2dcb24.png)
This is the file, that is mentioned in the message:
[crash-report-07_09_2021_14_42_03.txt](https://github.com/DeltaNedas/anuke-logic/files/6791410/crash-report-07_09_2021_14_42_03.txt)
The mod was the only mod active. In the log file are also some other mods mentioned, but they where all disabled.

**Comment by deltanedas** [comment]
no idea if this still applies, crash report gives no reference to my code
